<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Admin', 'doctrine');

/**
 * BaseAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property string $password
 * @property string $mod_permissions
 * @property string $cat_permissions
 * @property boolean $is_active
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property timestamp $logged_at
 * @property Doctrine_Collection $Content
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getEmail()           Returns the current record's "email" value
 * @method string              getPassword()        Returns the current record's "password" value
 * @method string              getModPermissions()  Returns the current record's "mod_permissions" value
 * @method string              getCatPermissions()  Returns the current record's "cat_permissions" value
 * @method boolean             getIsActive()        Returns the current record's "is_active" value
 * @method timestamp           getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()       Returns the current record's "updated_at" value
 * @method timestamp           getLoggedAt()        Returns the current record's "logged_at" value
 * @method Doctrine_Collection getContent()         Returns the current record's "Content" collection
 * @method Admin               setId()              Sets the current record's "id" value
 * @method Admin               setEmail()           Sets the current record's "email" value
 * @method Admin               setPassword()        Sets the current record's "password" value
 * @method Admin               setModPermissions()  Sets the current record's "mod_permissions" value
 * @method Admin               setCatPermissions()  Sets the current record's "cat_permissions" value
 * @method Admin               setIsActive()        Sets the current record's "is_active" value
 * @method Admin               setCreatedAt()       Sets the current record's "created_at" value
 * @method Admin               setUpdatedAt()       Sets the current record's "updated_at" value
 * @method Admin               setLoggedAt()        Sets the current record's "logged_at" value
 * @method Admin               setContent()         Sets the current record's "Content" collection
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('mod_permissions', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cat_permissions', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('logged_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Content', array(
             'local' => 'id',
             'foreign' => 'admin_id'));
    }
}