<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuizOption', 'doctrine');

/**
 * BaseQuizOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question_id
 * @property string $route
 * @property string $body
 * @property integer $point
 * @property integer $sort
 * @property integer $nb_love
 * @property timestamp $created_at
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method integer    getQuestionId()  Returns the current record's "question_id" value
 * @method string     getRoute()       Returns the current record's "route" value
 * @method string     getBody()        Returns the current record's "body" value
 * @method integer    getPoint()       Returns the current record's "point" value
 * @method integer    getSort()        Returns the current record's "sort" value
 * @method integer    getNbLove()      Returns the current record's "nb_love" value
 * @method timestamp  getCreatedAt()   Returns the current record's "created_at" value
 * @method QuizOption setId()          Sets the current record's "id" value
 * @method QuizOption setQuestionId()  Sets the current record's "question_id" value
 * @method QuizOption setRoute()       Sets the current record's "route" value
 * @method QuizOption setBody()        Sets the current record's "body" value
 * @method QuizOption setPoint()       Sets the current record's "point" value
 * @method QuizOption setSort()        Sets the current record's "sort" value
 * @method QuizOption setNbLove()      Sets the current record's "nb_love" value
 * @method QuizOption setCreatedAt()   Sets the current record's "created_at" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz_option');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('question_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('point', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nb_love', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}