<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Page', 'doctrine');

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property string $type
 * @property string $route
 * @property string $title
 * @property string $content
 * @property integer $sort
 * @property timestamp $created_at
 * @property boolean $is_active
 * @property integer $nb_love
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getCategoryId()  Returns the current record's "category_id" value
 * @method string    getType()        Returns the current record's "type" value
 * @method string    getRoute()       Returns the current record's "route" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method string    getContent()     Returns the current record's "content" value
 * @method integer   getSort()        Returns the current record's "sort" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method boolean   getIsActive()    Returns the current record's "is_active" value
 * @method integer   getNbLove()      Returns the current record's "nb_love" value
 * @method Page      setId()          Sets the current record's "id" value
 * @method Page      setCategoryId()  Sets the current record's "category_id" value
 * @method Page      setType()        Sets the current record's "type" value
 * @method Page      setRoute()       Sets the current record's "route" value
 * @method Page      setTitle()       Sets the current record's "title" value
 * @method Page      setContent()     Sets the current record's "content" value
 * @method Page      setSort()        Sets the current record's "sort" value
 * @method Page      setCreatedAt()   Sets the current record's "created_at" value
 * @method Page      setIsActive()    Sets the current record's "is_active" value
 * @method Page      setNbLove()      Sets the current record's "nb_love" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('nb_love', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}