<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Designer', 'doctrine');

/**
 * BaseDesigner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $first_letter
 * @property string $photo
 * @property string $biography
 * @property integer $sort
 * @property timestamp $created_at
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getFirstLetter()  Returns the current record's "first_letter" value
 * @method string    getPhoto()        Returns the current record's "photo" value
 * @method string    getBiography()    Returns the current record's "biography" value
 * @method integer   getSort()         Returns the current record's "sort" value
 * @method timestamp getCreatedAt()    Returns the current record's "created_at" value
 * @method Designer  setId()           Sets the current record's "id" value
 * @method Designer  setName()         Sets the current record's "name" value
 * @method Designer  setFirstLetter()  Sets the current record's "first_letter" value
 * @method Designer  setPhoto()        Sets the current record's "photo" value
 * @method Designer  setBiography()    Sets the current record's "biography" value
 * @method Designer  setSort()         Sets the current record's "sort" value
 * @method Designer  setCreatedAt()    Sets the current record's "created_at" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDesigner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('designer');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('first_letter', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('biography', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}