<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Coupon', 'doctrine');

/**
 * BaseCoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $file
 * @property string $route
 * @property string $title
 * @property string $body
 * @property string $image
 * @property integer $nb_print
 * @property boolean $is_active
 * @property timestamp $created_at
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getType()       Returns the current record's "type" value
 * @method string    getFile()       Returns the current record's "file" value
 * @method string    getRoute()      Returns the current record's "route" value
 * @method string    getTitle()      Returns the current record's "title" value
 * @method string    getBody()       Returns the current record's "body" value
 * @method string    getImage()      Returns the current record's "image" value
 * @method integer   getNbPrint()    Returns the current record's "nb_print" value
 * @method boolean   getIsActive()   Returns the current record's "is_active" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method Coupon    setId()         Sets the current record's "id" value
 * @method Coupon    setType()       Sets the current record's "type" value
 * @method Coupon    setFile()       Sets the current record's "file" value
 * @method Coupon    setRoute()      Sets the current record's "route" value
 * @method Coupon    setTitle()      Sets the current record's "title" value
 * @method Coupon    setBody()       Sets the current record's "body" value
 * @method Coupon    setImage()      Sets the current record's "image" value
 * @method Coupon    setNbPrint()    Sets the current record's "nb_print" value
 * @method Coupon    setIsActive()   Sets the current record's "is_active" value
 * @method Coupon    setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCoupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coupon');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('nb_print', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}