<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuizQuestion', 'doctrine');

/**
 * BaseQuizQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $quiz_id
 * @property string $route
 * @property integer $number
 * @property string $body
 * @property boolean $is_active
 * @property integer $sort
 * @property timestamp $created_at
 * @property integer $nb_love
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method integer      getQuizId()     Returns the current record's "quiz_id" value
 * @method string       getRoute()      Returns the current record's "route" value
 * @method integer      getNumber()     Returns the current record's "number" value
 * @method string       getBody()       Returns the current record's "body" value
 * @method boolean      getIsActive()   Returns the current record's "is_active" value
 * @method integer      getSort()       Returns the current record's "sort" value
 * @method timestamp    getCreatedAt()  Returns the current record's "created_at" value
 * @method integer      getNbLove()     Returns the current record's "nb_love" value
 * @method QuizQuestion setId()         Sets the current record's "id" value
 * @method QuizQuestion setQuizId()     Sets the current record's "quiz_id" value
 * @method QuizQuestion setRoute()      Sets the current record's "route" value
 * @method QuizQuestion setNumber()     Sets the current record's "number" value
 * @method QuizQuestion setBody()       Sets the current record's "body" value
 * @method QuizQuestion setIsActive()   Sets the current record's "is_active" value
 * @method QuizQuestion setSort()       Sets the current record's "sort" value
 * @method QuizQuestion setCreatedAt()  Sets the current record's "created_at" value
 * @method QuizQuestion setNbLove()     Sets the current record's "nb_love" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuizQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz_question');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('quiz_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nb_love', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}