<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Quiz', 'doctrine');

/**
 * BaseQuiz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $content_id
 * @property string $title
 * @property string $route
 * @property string $body
 * @property integer $sort
 * @property integer $nb_love
 * @property boolean $is_active
 * @property boolean $is_featured
 * @property timestamp $created_at
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getContentId()   Returns the current record's "content_id" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method string    getRoute()       Returns the current record's "route" value
 * @method string    getBody()        Returns the current record's "body" value
 * @method integer   getSort()        Returns the current record's "sort" value
 * @method integer   getNbLove()      Returns the current record's "nb_love" value
 * @method boolean   getIsActive()    Returns the current record's "is_active" value
 * @method boolean   getIsFeatured()  Returns the current record's "is_featured" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method Quiz      setId()          Sets the current record's "id" value
 * @method Quiz      setContentId()   Sets the current record's "content_id" value
 * @method Quiz      setTitle()       Sets the current record's "title" value
 * @method Quiz      setRoute()       Sets the current record's "route" value
 * @method Quiz      setBody()        Sets the current record's "body" value
 * @method Quiz      setSort()        Sets the current record's "sort" value
 * @method Quiz      setNbLove()      Sets the current record's "nb_love" value
 * @method Quiz      setIsActive()    Sets the current record's "is_active" value
 * @method Quiz      setIsFeatured()  Sets the current record's "is_featured" value
 * @method Quiz      setCreatedAt()   Sets the current record's "created_at" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuiz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('content_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nb_love', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('is_featured', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}