<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Video', 'doctrine');

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $object_type
 * @property integer $object_id
 * @property string $title
 * @property string $description
 * @property string $thumb
 * @property string $embed
 * @property integer $sort
 * @property integer $iscover
 * @property integer $is_featured
 * @property timestamp $created_at
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getObjectType()  Returns the current record's "object_type" value
 * @method integer   getObjectId()    Returns the current record's "object_id" value
 * @method string    getTitle()       Returns the current record's "title" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method string    getThumb()       Returns the current record's "thumb" value
 * @method string    getEmbed()       Returns the current record's "embed" value
 * @method integer   getSort()        Returns the current record's "sort" value
 * @method integer   getIscover()     Returns the current record's "iscover" value
 * @method integer   getIsFeatured()  Returns the current record's "is_featured" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method Video     setId()          Sets the current record's "id" value
 * @method Video     setObjectType()  Sets the current record's "object_type" value
 * @method Video     setObjectId()    Sets the current record's "object_id" value
 * @method Video     setTitle()       Sets the current record's "title" value
 * @method Video     setDescription() Sets the current record's "description" value
 * @method Video     setThumb()       Sets the current record's "thumb" value
 * @method Video     setEmbed()       Sets the current record's "embed" value
 * @method Video     setSort()        Sets the current record's "sort" value
 * @method Video     setIscover()     Sets the current record's "iscover" value
 * @method Video     setIsFeatured()  Sets the current record's "is_featured" value
 * @method Video     setCreatedAt()   Sets the current record's "created_at" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_type', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('object_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('thumb', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('embed', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('iscover', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_featured', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}