<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/04 11:00:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=girasole',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
