<?php

/**
 * AphorismTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AphorismTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AphorismTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Aphorism');
    }
    
    public function doExecute($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        
        return $q->execute();
    }
    
  
    public function doFetchArray($params = array())
    {
        $q = Doctrine_Query::create()->select('id, text, source, sort, created_at');
        $q = self::params($q, $params);
                
        return $q->fetchArray();
    }
    
    
    public function doFetchSelection($params = array())
    {
        $res = array();
        $rss = self::doFetchArray($params);
        foreach ($rss as $rs)
        {
          $res[$rs['id']] = $rs['link'];
        }
        return $res;
    }
  
    
    public function doFetchOne($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        return $q->fetchOne();
    }
    
  
    
    public function getPager($params = array(), $page=1)
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        $pager = new sfDoctrinePager('Aphorism', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
    
    
    private function params($q, $params = array())
    {
        $q->from('Aphorism');
        $q->where('id <> ? ', (isset($params['id']) && $params['id'] ? $params['id'] : 0));
  
        if(isset($params['keyword']) && $params['keyword'])
            $q->andWhere('text LIKE ? OR source LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
        
        $limit = isset($params['limit']) ? $params['limit'] : sfConfig::get('app_pager', 30);
        $q->limit($limit);
        
        $q->orderBy('sort DESC, created_at ASC');
  
        return $q;
    }
}