<?php

/**
 * Content
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    barilga
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Content extends BaseContent
{

    public function __toString()
    {
        return $this->getTitle();
    }
	
	
    public function getAuthor()
    {
        $rs = Doctrine::getTable('User')->doFetchOne(array('id'=>$this->getAuthorId()));
		    return $rs['username'];
    }
	
    public function getPhotographer()
    {
        $rs = Doctrine::getTable('User')->doFetchOne(array('id'=>$this->getPhotographerId()));
		    return $rs['username'];
    }
}