<?php

/**
 * DesignerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DesignerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DesignerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Designer');
    }
}