<?php

/**
 * DiscussMirrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscussMirrorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiscussMirrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiscussMirror');
    }
    
    public function delete($ids)
    {
        $q = Doctrine_Query::create()
              ->delete()
              ->from('DiscussMirror')  
              ->whereIn('id', $ids)
              ->execute();
    }
    
    public function doExecute($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        
        return $q->execute();
    }
    
  
    public function doFetchArray($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        return $q->fetchArray();
    }
    
    
    public function doFetchSelection($params = array())
    {
        $res = array();
        $rss = self::doFetchArray($params);
        foreach ($rss as $rs)
        {
          $res[$rs['id']] = $rs['link'];
        }
        return $res;
    }
  
    
    public function doFetchOne($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        return $q->fetchOne();
    }
    
    
    public function doCount($params = array())
    {
        $q = Doctrine_Query::create()->select('count(id)');
        $q = self::params($q, $params);
        return $q->count();
    }
  
    
    public function getPager($params = array(), $page=1)
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        $pager = new sfDoctrinePager('DiscussMirror', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
    
    
    private function params($q, $params = array())
    {
        $q->from('DiscussMirror');
  
        if(isset($params['id']) && $params['id'] != null)
            $q->andWhere('id= ?', $params['id']);

        if(isset($params['objectType']) && $params['objectType'] != null)
            $q->andWhere('object_type= ?', $params['objectType']);
            
        if(isset($params['objectId']) && $params['objectId'] != null)
            $q->andWhere('object_id= ?', $params['objectId']);
            
        if(isset($params['name']) && $params['name'] != null)
            $q->andWhere('name= ?', $params['name']);
            
        if(isset($params['ip_address']) && $params['ip_address'] != null)
            $q->andWhere('ip_address= ?', $params['ip_address']);
            
        if(isset($params['text']) && $params['text'])
            $q->andWhere('text= ?', $params['text']);

        if(isset($params['keyword']) && $params['keyword'])
            $q->andWhere('text LIKE ? OR name LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
        
        // group, offset, limit, order
        if(isset($params['groupBy']) && $params['groupBy'])
            $q->groupBy($params['groupBy']);        

        if(isset($params['offset']) && $params['offset'])
            $q->offset($params['offset']);
        
        $limit = isset($params['limit']) ? $params['limit'] : sfConfig::get('app_limit', 30);
        $q->limit($limit);
  
        $order = isset($params['orderBy']) ? $params['orderBy'] : 'created_at DESC';
        $q->orderBy($order);
  
        return $q;
    }
}