<?php

/**
 * Poll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Poll extends BasePoll
{

    public function __toString()
    {
        return $this->getTitle();
    }
    
    public function getTotalPercent()
    {
        $rss = $this->getOptions();
        $total = 0;
        foreach ($rss as $rs){
            $total += $rs['nb_vote'];
        }
        return $total;
    }
    
    public function getContent() {
        return Doctrine::getTable('Content')->doFetchOne(array('id'=>$this->getObjectId()));
    }

    public function getOptions()
    {
        return Doctrine::getTable('PollOption')->doFetchArray(array('pollId'=>$this->getId()));
    }

}