<?php

/**
 * QuizAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizAnswer');
    }
    
    
    public function doExecute($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        
        return $q->execute();
    }
    
  
    public function doFetchArray($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        return $q->fetchArray();
    }
    
    
    public function doFetchSelection($params = array())
    {
        $res = array();
        $rss = self::doFetchArray($params);
        foreach ($rss as $rs)
        {
          $res[$rs['id']] = $rs['title'];
        }
        return $res;
    }
  
    
    public function doFetchOne($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        return $q->fetchOne();
    }
    
  
    public function doCount($params = array())
    {
        $q = Doctrine_Query::create()->select('count(id)');
        $q = self::params($q, $params);
        return $q->count();
    }
    
    public function getPager($params = array(), $page=1)
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        $pager = new sfDoctrinePager('QuizAnswer', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
    
    
    private function params($q, $params = array())
    {
        $q->from('QuizAnswer');
  
        if(isset($params['id']) && $params['id'] != null)
            $q->andWhere('id= ?', $params['id']);
            
        if(isset($params['route']) && $params['route'] != null)
            $q->andWhere('route= ?', $params['route']);
        
        if(isset($params['quizId']) && $params['quizId'] != null)
            $q->andWhere('quiz_id= ?', $params['quizId']);
            
        if(isset($params['point']) && $params['point'] != null)
            $q->andWhere('point_start <= ?', $params['point']);
            
        if(isset($params['point']) && $params['point'] != null)
            $q->andWhere('point_end >= ?', $params['point']);
            
        if(isset($params['body']) && $params['body'] != null)
            $q->andWhere('body like ?', '%'.$params['body'].'%');

        if(isset($params['keyword']) && $params['keyword'])
            $q->andWhere('title LIKE ? OR body LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
            
        // is_active
        if(isset($params['isActive'])) {
            if($params['isActive'] != "all" && in_array($params['isActive'], array('0', '1'))) // all ued filter hiihgui
                $q->andWhere('is_active = ?', $params['isActive']);
        } else {
            $q->andWhere('is_active = ?', 1); // default
        }

        // group, offset, limit, order
        if(isset($params['groupBy']) && $params['groupBy'])
            $q->groupBy($params['groupBy']);        

        if(isset($params['offset']) && $params['offset'])
            $q->offset($params['offset']);
        
        $limit = isset($params['limit']) ? $params['limit'] : sfConfig::get('app_limit', 30);
        $q->limit($limit);
  
        $order = isset($params['orderBy']) ? $params['orderBy'] : 'sort DESC, created_at ASC, point_start ASC';
        $q->orderBy($order);

        return $q;
    }
}