<?php

/**
 * QuizQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class QuizQuestion extends BaseQuizQuestion
{
    public function __toString()
    {
        return $this->getBody();
    }

    public function getOptions($limit = 30)
    {
        return Doctrine::getTable('QuizOption')->doFetchArray(array('questionId'=>$this->getId(), 'limit'=>$limit));
    }
}