<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
    
    public function doExecute($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        
        return $q->execute();
    }
    
  
    public function doFetchArray($params = array())
    {
        $q = Doctrine_Query::create()->select('id, title, category_id, company_id, folder, filename');
        $q = self::params($q, $params);
                
        return $q->fetchArray();
    }
    
    
    public function doFetchSelection($params = array())
    {
        $res = array();
        $rss = self::doFetchArray($params);
        foreach ($rss as $rs)
        {
          $res[$rs['id']] = $rs['title'];
        }
        return $res;
    }
  
    
    public function doFetchOne($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        return $q->fetchOne();
    }
    
  
    
    public function getPager($params = array(), $page=1)
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        $pager = new sfDoctrinePager('User', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
    
    
    private function params($q, $params = array())
    {
        $q->from('User');
        $q->where('id <> ? ', (isset($params['id']) && $params['id'] ? $params['id'] : 0));
  
        if(isset($params['firstname']) && $params['firstname'])
            $q->andWhere('firstname= ?', '%'.$params['firstname'].'%');
            
        if(isset($params['lastname']) && $params['lastname'])
            $q->andWhere('lastname= ?', '%'.$params['lastname'].'%');

        if(isset($params['email']) && $params['email'])
            $q->andWhere('email= ?', '%'.$params['email'].'%');
        
        if(isset($params['mobile']) && $params['mobile'])
            $q->andWhere('mobile= ?', '%'.$params['mobile'].'%');
            
        if(isset($params['address']) && $params['address'])
            $q->andWhere('address LIKE ?', '%'.$params['address'].'%');
            
        if(isset($params['keyword']) && $params['keyword'])
            $q->andWhere('firstname LIKE ? OR lastname LIKE ? OR email LIKE ? OR mobile LIKE ? address LIKE ?', 
                array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%', '%'.$params['keyword'].'%', '%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
  
        if(isset($params['isFeatured']) && in_array($params['isFeatured'], array('0', '1'))) 
            $q->andWhere('is_featured = ?', $params['isFeatured']);
        
        if(isset($params['isActive']) && in_array($params['isActive'], array('0', '1'))) 
            $q->andWhere('is_active = ?', $params['isActive']);
        
        $limit = isset($params['limit']) ? $params['limit'] : sfConfig::get('app_pager', 30);
        $q->limit($limit);
        
        $q->orderBy('created_at DESC');
  
        return $q;
    }
}