<?php

/**
 * CouponPrintTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CouponPrintTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CouponPrintTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CouponPrint');
    }
}