<?php

/**
 * CouponCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CouponCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CouponCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CouponCode');
    }
}