<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Image extends BaseImage
{
  public function __toString()
  {
      return $this->getTitle();
  }
    
  public function getFullPath($prefix=0)
  {
      $folder = $this->getFolder();
      $upload_dir = sfConfig::get('sf_upload_dir').'/'.$folder.'/';
      $filename = $folder.'/'.$this->getFilename();

      // check  thumb & get it
      if($prefix && file_exists($upload_dir.$prefix.'-'.$this->getFilename())) 
          $filename = $folder.'/'.$prefix.'-'.$this->getFilename();
      
      // main image not exists
      if(!file_exists($upload_dir.'/'.$this->getFilename()))
          $filename = 'image_default/default.gif';

      return $filename;
  }
}