<?php

/**
 * RunwayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RunwayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RunwayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Runway');
    }
}